### ISSUE TITLE
Add a dataset (tree + alternatives) generator

### ISSUE THREAD

**Issue by jpierre03** [Taeradan/hahp#11]
For testing purpose, add :
- a matrix generator ( random values ? )
- a complete ahp tree (uniform and non uniform distribution, several levels)

**Comment by Taeradan** [comment]
We also should generate the alternatives related to the tree to allow us to actually test the tree.

**Comment by Taeradan** [comment]
It seems a good idea to add a new "AHPDataSet = (AHPTree, [Alternative])" type to simplify some function signatures.

**Comment by Taeradan** [comment]
First results (Intel core i7 4790K, 16Go DDR3) (obtained with `make profile`):
- reference result
  - 3 levels, 5 children by level, 1000 alternatives : 2.7s
- "levels" variations
  - 1 levels, 5 children by level, 1000 alternatives : 0.18s
  - 2 levels, 5 children by level, 1000 alternatives : 0.55s
  - 3 levels, 5 children by level, 1000 alternatives : 2.7s
  - 4 levels, 5 children by level, 1000 alternatives : 14.5s
  - 5 levels, 5 children by level, 1000 alternatives : 1m48s
- "children by level" variations
  - 3 levels, 5 children by level, 1000 alternatives : 2.7s
  - 3 levels, 10 children by level, 1000 alternatives : 11.3s
  - 3 levels, 15 children by level, 1000 alternatives : 26s
  - 3 levels, 20 children by level, 1000 alternatives : 53s
- "alternatives" variations
  - 3 levels, 5 children by level, 100 alternatives : 0.15s
  - 3 levels, 5 children by level, 500 alternatives : 1.05s
  - 3 levels, 5 children by level, 1000 alternatives : 2.7s
  - 3 levels, 5 children by level, 5000 alternatives : 47s
  - 3 levels, 5 children by level, 10000 alternatives : 2m56s
