### ISSUE TITLE
import and export configuration as xml files

### ISSUE THREAD

**Issue by jpierre03** [Taeradan/hahp#8]
From our last implementation of AHP (https://github.com/Taeradan/JenericAHP) we have some xml files and Academic datasets.

It could be a great idea to create an import/export module to read/write thoses dataset.

XML definition (DTD)
- https://github.com/Taeradan/JenericAHP/blob/master/GenericAHP/src/org/taeradan/ahp/conf/ahp_conf.dtd

XML Example
- https://github.com/Taeradan/JenericAHP/blob/master/GenericAHP/src/org/taeradan/ahp/conf/ahp_conf.xml
- https://github.com/Taeradan/JenericAHP/blob/master/GenericAHP/src/org/taeradan/ahp/conf/empty_ahp.xml

**Comment by jpierre03** [comment]
@Taeradan Maybe a script to convert existent .xml to .json might be a better idea.
XML won't be used as a first class format but rather as an obsolete one.

**Comment by Taeradan** [comment]
If we really want an old example, we will import it by hand. XML is too tricky to import (in any language...).
